#!/bin/bash
# Criado por: Guilherme Schneider_Leon_Renã Cruz.
# Editado por:    Na data:
# Data: 07112021


echo "\n#####################################################################################"
echo "Para o Script rodar deve ter as seguintes ferramentas: subfinder, assetfinder, amass"
echo "\n#####################################################################################"


#Entra com o dominio para fazer o recon
echo "Digite o dominio a ser feito o Recon:"
read dom
echo "começando o reconhecimento de $dom"

## Cria os caminhos para salvar as saidas
mkdir -p $HOME/recon
mkdir -p $HOME/recon/a17
echo "Os logs com as saidas podem ser encontrados em $HOME/recon/a17"


## usando subfinder para recon
echo "Usando o subfinder para recon"
subfinder -silent -d $dom > $HOME/recon/a17/subfinder.txt

## usando assetfinder para recon
echo "Usando o assetfinder para recon"
assetfinder $dom > $HOME/recon/a17/assetfinder.txt

## usando amass para recon
echo "Usando o amass para recon"
amass enum -d $dom > $HOME/recon/a17/amass.txt

# Organizar as saídas das ferramentas de forma a construir um único arquivo

paste -d '\n' -s $HOME/recon/a17/subfinder.txt $HOME/recon/a17/assetfinder.txt $HOME/recon/a17/amass.txt > $HOME/recon/a17/subdom_final.txt

# Usando o HTTPROBE
echo "Comecando testes de funcionalidade do subdominios:"
echo "Logs serao salvos em XXX"
cat $HOME/recon/a17/subdom_final.txt | httprobe > $HOME/recon/a17/httprobe.txt 
echo "Finalizado o testes de funcionalidade dos subdominios"

# Para os subdomínios vivos, tirar print das telas e salvar em uma pasta específica.

# GoWitness
#mkdir -p $HOME/recon/a17/screenrecord 
#cd $HOME/recon/a17/screenrecord 
#gowitness $HOME/recon/a17/httprobe.txt

#./EyeWitness/Python/EyeWitness.py -f files/alive --no-prompt -d prints --web

# Procurar uma forma de salvar e mostrar os subdomínios identificados e as tecnologias que são usadas por cada um.

eyewitness -f $HOME/recon/a17/httprobe.txt --no-prompt -d screenshot --web

