#!/bin/bash
# Criado por: Guilherme Schneider_Leon_Renã Cruz.
# Editado por:    Na data:
# Data: 07112021

#Entra com o dominio para fazer o recon
echo "Digite o dominio a ser feito o Recon:"
read dom
echo "começando o reconhecimento de $dom"

## Cria os caminhos para salvar as saidas
mkdir -p $HOME/recon
mkdir -p $HOME/recon/a17
echo "Os logs com as saidas podem ser encontrados em $HOME/recon/a17"

## Verificar se o GO estah instalado (usado para rodar as ferramentas)
## Verificar se o subfinder estah instalado (pergunta se quer instalar)
## Verificar se o assetfinder estah instalado (pergunta se quer instalar)
## Verificar se o amass esta instalado (pergunta se quer instalar)
    #  nome=amass
    #  teste=`ls /etc/init.d/$nome`;
    #  if [ $teste ] 
    #  then
    #    $teste status
    #  else
    #    apt-get install amass
    #  fi


## usando subfinder para recon
subfinder -silent -d $dom >> $HOME/recon/a17/subfinder.txt

## usando assetfinder para recon
#ssetfinder $1 >> $HOME/recon/a17/assetfinder.txt

## usando amass para recon
#amass enum -d $1 >> $HOME/recon/a17/amass.txt

# Organizar as saídas das ferramentas de forma a construir um único arquivo

#paste -d '\n' -s $HOME/recon/a17/subfinder.txt $HOME/recon/a17/assetfinder.txt $HOME/recon/a17/amass.txt >> $HOME/recon/a17/subdom_final.txt





###### parei aqui #########

# Verificar quais os subdomínios estão “vivos” e se estão usando http ou https.
# httprobe
#sort files/subdomains | uniq | httprobe > files/alive

# Para os subdomínios vivos, tirar print das telas e salvar em uma pasta específica.
# GoWitness

#./EyeWitness/Python/EyeWitness.py -f files/alive --no-prompt -d prints --web

# Procurar uma forma de salvar e mostrar os subdomínios identificados e as tecnologias que são usadas por cada um.
